#!/usr/bin/env bash

set -e

## configuration ##
RELEASE=bookworm

# TODO move all the logic into another script, probably python as argument
# splitting is a pain
args=(
    --mode debian # TODO should i leave mode debian?
    --system live
    --distribution "$RELEASE"
    --architectures amd64
    --archive-areas "main,contrib,non-free,non-free-firmware"

    # enable additional repository areas
    --updates true
    --security true
    --backports true

    --binary-images iso-hybrid
    --binary-filesystem ext4

    # ISO options
    --iso-application "'Galena Rescue'"
    --iso-publisher "'galena-linux'"
    --iso-volume "'Galena Rescue'"

    --bootappend-live "'boot=live config splash'"

    --memtest memtest86+
    --win32-loader true

    --debootstrap-options "'--include=apt-transport-https,ca-certificates,openssl'"

    --apt-indices false
    --zsync false
    --net-tarball false
    --source false

    --clean
)

lb config noauto "${args[@]}" "$@"

