#!/bin/sh
#
# https://github.com/sandorex/galena-linux
# galena linux rescue live-build config

set -e

# source globals
. ../common/common.sh

export ISO_LABEL="Galena Rescue $VERSION $TIMESTAMP"
export ISO_IMAGE_NAME="galena-rescue-$VERSION"
export GRUB_TITLE="$ISO_LABEL ($RELEASE)"

# the script that has all the common functionality
../common/config.sh "$@"

