#!/bin/sh
#
# https://github.com/sandorex/galena-linux
# galena linux installer live-build config

set -e

# source common things
. ../common/config.sh

ISO_LABEL="Galena Installer $VERSION $TIMESTAMP"
ISO_VOLUME="Galena Linux"
ISO_IMAGE_NAME="${IMAGE_NAME_PREFIX}-installer-${IMAGE_NAME_SUFFIX}"

if [ "${#ISO_VOLUME}" -gt 16 ]; then
    echo "Invalid ISO volume, longer than 16 characters"
    exit 1
fi

# copy the common files with force overwrite
cp -fr ../common/config ./

lb config noauto \
    --system live \
    --image-name "$ISO_IMAGE_NAME" \
    --distribution "$RELEASE" \
    --architectures amd64 \
    --archive-areas "main,contrib,non-free,non-free-firmware" \
    --apt-source-archives false \
    --apt-options "--yes -o 'Acquire::ForceIPv4=true'" \
    --updates true \
    --security true \
    --backports true \
    --binary-images iso-hybrid \
    --binary-filesystem ext4 \
    --iso-application "$ISO_LABEL" \
    --iso-volume "$ISO_VOLUME" \
    --iso-publisher "$ISO_PUBLISHER" \
    --debian-installer live \
    --debian-installer-distribution "$RELEASE" \
    --debian-installer-gui true \
    --bootappend-live "boot=live components config" \
    --memtest memtest86+ \
    --debootstrap-options "--include=apt-transport-https,ca-certificates,openssl" \
    --apt-indices false \
    --cache-indices true \
    --zsync false \
    --net-tarball false \
    --clean \
    --color \
    "$@"

