#!/bin/sh
#
# https://github.com/sandorex/galena-linux
# galena linux installer live-build config

set -e

# source globals
. ../common/common.sh

export ISO_LABEL="Galena Installer $VERSION $TIMESTAMP"
export ISO_IMAGE_NAME="galena-installer-$VERSION"
export GRUB_TITLE="$ISO_LABEL ($RELEASE)"

# the script that has all the common functionality
# ipv6 for some reason breaks downloads for installer stuff
../common/config.sh \
    --debian-installer live \
    --debian-installer-distribution "$RELEASE" \
    --debian-installer-gui true \
    "$@"
