name: iso-builder

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

# running docker did not quite work so i am just running a new debian container
# and installing the live-build, fix this and use just for ci builds too

jobs:
  build-installer:
    runs-on: ubuntu-22.04

    container:
      image: debian:latest
      volumes:
        - /proc:/proc
      options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install live-build
        run: |
          apt update
          apt-get -y install live-build

      - name: Build Installer ISO
        run: |
          cd installer

          lb clean && lb config && lb build

      - uses: actions/upload-artifact@v3
        with:
          name: installer-build-log
          path: **/build.log

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Development Build
          fail_on_unmatched_files: yes
          files: |
            *.iso

  build-rescue:
    runs-on: ubuntu-22.04

    container:
      image: debian:latest
      volumes:
        - /proc:/proc
      options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install live-build
        run: |
          apt update
          apt-get -y install live-build

      - name: Build Rescue ISO
        run: |
          cd rescue

          lb clean && lb config && lb build

      - uses: actions/upload-artifact@v3
        with:
          name: rescue-build-log
          path: **/build.log

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Development Build
          fail_on_unmatched_files: yes
          files: |
            *.iso
